"""Tennis terminology glossary for bilingual translation."""

GLOSSARY = {
    # Core FTT concepts
    "fault tolerant": "容错",
    "fault tolerance": "容错性",
    "margin for error": "容错空间",
    "fundamental theorem": "基本定理",
    "fundamental theorem of tennis": "网球基本定理",
    # Contact & racket
    "string angle": "拍面角度",
    "racket-forearm angle": "球拍-前臂夹角",
    "contact point": "击球点",
    "contact": "击球接触",
    "racket head": "拍头",
    "butt cap": "拍柄底盖",
    "swing path": "挥拍路径",
    "racket face": "拍面",
    "rolling the racket": "翻转球拍",
    "roll over it": "翻转压拍",
    # Grips
    "semi-western grip": "半西方式握拍",
    "eastern grip": "东方式握拍",
    "western grip": "西方式握拍",
    "continental grip": "大陆式握拍",
    "grip": "握拍",
    # Spin
    "topspin": "上旋",
    "backspin": "下旋",
    "slice": "切削",
    "windshield wiper": "雨刷式",
    # Preparation
    "unit turn": "整体转体",
    "backswing": "引拍",
    "hand preparation": "手部准备",
    "preparing the hand": "手部准备",
    "wrist lag": "手腕滞后",
    "elbow extension": "肘部伸展",
    "visual tracking": "视觉追踪",
    "inhale and wait": "吸气等待",
    # Stances
    "closed stance": "关闭式站位",
    "open stance": "开放式站位",
    "neutral stance": "中性站位",
    # Forward swing
    "forward swing": "前挥",
    "follow-through": "随挥",
    "rotational kinetic chain": "旋转动力链",
    "kinetic chain": "动力链",
    "abdominal coil": "腹部蓄力",
    "out vector": "Out向量",
    "up vector": "Up向量",
    "through vector": "Through向量",
    "out, up, and through": "Out、Up、Through三向量",
    "hip rotation": "髋旋转",
    "shoulder rotation": "肩旋转",
    "hip-shoulder separation": "肩髋分离角",
    "lead with the hips": "以髋部引导",
    # Anatomy
    "pronation": "旋前",
    "supination": "旋外",
    "non-hitting arm": "非持拍臂",
    "non-hitting hand": "非持拍手",
    "hitting arm": "持拍臂",
    "wrist tension": "手腕张力",
    # Training
    "drop feed": "抛球喂球",
    "live-ball": "活球对打",
    "mini-tennis": "迷你网球（短距离对打）",
    "shadow swing": "空挥（影子挥拍）",
    "offense-defense": "攻防练习",
    "X-drill": "X训练法",
    # General tennis
    "stroke production": "击球动作",
    "movement pattern": "运动模式",
    "coaching cue": "教学提示",
    "power limit": "力量上限",
    "rally": "回合",
    "baseline": "底线",
    "net": "球网",
    "cross-court": "斜线球",
    "down-the-line": "直线球",
    "passing shot": "穿越球",
    "pusher": "磨控型选手",
    # ===== Bourne "One Minute Tennis Forehand Solution" 专属术语 =====
    # 4 个核心 cue（保留英文术语 + 中文括注）
    "Hold the ball": "Hold the ball（抱球）",
    "hold the ball": "Hold the ball（抱球）",
    "hold onto the ball": "Hold onto the ball（抱住球）",
    "Holding Up": "Holding Up（架拍保持）",
    "hold it up": "Hold it Up（拍头撑住）",
    "Power Point": "Power Point（拍喉触觉锚点）",
    "BOUNCE": "BOUNCE（拍弹感）",
    "Find the bounce": "Find the bounce（寻找拍弹感）",
    "Feel the bounce": "Feel the bounce（感受拍弹感）",
    "Use the bounce": "Use the bounce（使用拍弹感）",
    "raise your heels": "抬脚跟",
    "raise the heels": "抬脚跟",
    "don't bend your knees": "不要主动屈膝",
    "Place the hand": "Place（放置手位）",
    "pull forward": "Pull Forward（向前拉）",
    "place, pull": "Place, Pull（放置-拉）",
    # Take-back / 引拍
    "take-back": "引拍",
    "takeback": "引拍",
    "take back": "引拍",
    "elbow first": "肘先（先抬肘）",
    "racket first": "拍头先（错误模式）",
    "loop": "Loop（循环引拍）",
    "Reference Point": "Reference Point（参考点）",
    "five reference points": "五个参考点",
    "5 commonalities": "5 大共同性",
    "five commonalities": "5 大共同性",
    "fundamental commonalities": "基本共同性",
    "load weight": "装载重量",
    "load weight into": "装载重量到",
    "outside foot": "外侧脚",
    "weight on the outside foot": "重心在外侧脚",
    # Swing path / 挥拍路径
    "swing path": "挥拍路径",
    "low to high": "由低到高",
    "throat of the racket": "拍喉",
    "racket throat": "拍喉",
    "finger to thumb": "食指到拇指",
    "index finger": "食指",
    "thumb": "拇指",
    # Wrist
    "wrist snap": "手腕挥击（错误说法）",
    "loose wrist": "松腕",
    "loose grip": "松握",
    "wrist angle": "腕角",
    "constant wrist angle": "腕角恒定",
    "32 muscles": "32 块肌肉",
    "27 bones": "27 块骨头",
    # Serve bonus
    "trophy position": "举拍位（trophy 位）",
    "racket drop": "拍头下沉",
    "ball toss": "抛球",
    "knee bend": "屈膝",
    "leg drive": "蹬腿",
    "ankle drive": "踝主动",
    # Methodology / philosophy
    "active vs passive": "主动 vs 被动",
    "active movement": "主动动作",
    "passive result": "被动结果",
    "byproduct": "副产品",
    "kinematic byproduct": "动力学副产品",
    "Language of the Mind": "心智语言",
    "Language of the Body": "身体语言",
    "feel": "体感",
    "feeling": "体感",
    "single image": "单一意象",
    "single cue": "单一口令",
    # Pros referenced
    "Federer": "费德勒",
    "Nadal": "纳达尔",
    "Djokovic": "德约科维奇",
    "Sinner": "辛纳",
    "Alcaraz": "阿尔卡拉斯",
    "Sampras": "桑普拉斯",
}

def build_glossary_prompt() -> str:
    """Build glossary section for translation prompt."""
    lines = ["TENNIS TERMINOLOGY GLOSSARY (use these translations exactly):"]
    for en, zh in GLOSSARY.items():
        lines.append(f"  {en} = {zh}")
    return "\n".join(lines)
